# Data Structure

<h2>Soal 1: Perbedaan Data Structure</h2>

Jawab Pertanyaan di bawah ini:

Jelaskan perbedaan dari List, Tuple, Set dan Dictionary!

<b>List</b> <br>
Merupakan tipe data berurut yang anggotanya dapat berasal dari berbagai tipe data, cara membuatnya dengan diawali dan diakhiri tanda kurung siku. Selain itu list juga masuk dalam kategori struktur data.

<b>Tuple</b> <br>
Sama seperti string dan list, merupakan anggota tipe data berurut, cara membuatnya dengan menggunakan kurung biasa atau tanpa tanda kurung.

<b>Set</b> <br>
Satu-satunya anggota tipe data tak berurut dikarenakan set tidak mengenal indeks, membuat posisi tiap anggotanya tak jelas. Selain itu set punya sifat anggota yang unik artinya anggota satu dan yang lain tidak akan ada yang sama. Jika ada yang sama (duplikasi) maka akan dihapus salah satu. Cara membuatnya dengan menggunakan kurung kurawal.

<b>Dictionary</b> <br>
Tipe data yang cara membuatnya sama seperti set membutuhkan tanda kurung kurawal, bedanya dalam dictionary anggotanya tersusun atas dua atribut key dan value yang keduanya ini dipisahkan denga tanda titik dua (key:value). Key dapat bertindak sebagai indeks jadi nilainya harus bersifat unik.




---



---



# List

<h2>Soal 2: Akses List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [4]:
a = ['1', '13b', 'aa1', 1.32, 22.1, 2.34]
# slicing list
print(a[1:5])

['13b', 'aa1', 1.32, 22.1]


Expected Output :

[ '13b', 'aa1', 1.32, 22.1 ]

<h2>Soal 3: Akses Nested List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [6]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# subsetting list
print(a[1][-2:])

[0, 6]


Expected Output :


[0, 6]

<h2>Soal 4: List Manipulation</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [8]:
a = [
    [5, 9, 8],
    [0, 0, 6]
    ]
# change list value
a[0][2] = 10
a[1][0] = 11 

print(a)

[[5, 9, 10], [11, 0, 6]]


Expected Output :

[ [5, 9, 10], [11, 0, 6] ]

<h2>Soal 5: Delete Element List</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [13]:
areas = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

# Hilangkan elemen yang bernilai "bathroom" dan 10.50 dalam satu statement code
del(areas[8:10])

print(areas)

['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'poolhouse', 24.5, 'garage', 15.45]


Expected Output:

['hallway',
 11.25,
 'kitchen',
 18.0,
 'chill zone',
 20.0,
 'bedroom',
 10.75,
 'poolhouse',
 24.5,
 'garage',
 15.45]



## Soal 6: List Comprehension

Gunakan metode **list comprehension** untuk mencari anggota dari S yang habis di bagi 2, kemudian assign hasilnya dalam bentuk list ke dalam variabel T.

In [15]:
S = [0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

T = [i for i in S if i %2 == 0]

print(T)

[0, 4, 16, 36, 64]


Expected Output:

[0, 4, 16, 36, 64]



---



---



# Tuple

## Soal 7. Mengakses Tuple

Gunakan cara sclicing untuk mengakses tuple sehingga mendapatkan hasil sesuai expected output

In [20]:
tuple_1 = (1, 2, 6, 7, 8, 9, 10)

#akses tuple
print(tuple_1[2:5])

(6, 7, 8)


Expected Outpout:


(6, 7, 8)



---



---



# Dictionary

<h2>Soal 8: Menambahkan key-value baru ke Dictionary</h2>

Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [21]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'berlin', 'norway':'oslo' }

# tambahkan key itali ke objek dictionary dengan value roma
europe['italy']='Roma'
print(europe)

# cek apakah itali ada di dalam objek dictionary


{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'Roma'}


Expected Output:
    
True

<h2>Soal 9: Update dan Remove Dictinary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [23]:
europe = {'spain':'madrid', 'france':'paris', 'germany':'bonn',
          'norway':'oslo', 'italy':'rome', 'poland':'warsaw',
          'australia':'vienna' }

# update nilai ibukota german ke berlin
europe['germany'] = 'berlin'

# remove australia dari europa
del europe['australia']

print(europe)

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}


Expected Output:

{'spain': 'madrid', 'france': 'paris', 'germany': 'berlin', 'norway': 'oslo', 'italy': 'rome', 'poland': 'warsaw'}

<h2>Soal 10: Nested Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [32]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 } 
         }

# berapa populasi dari kota german?
print(country['germany'].values())
# update data baru, yaitu negara indonesia dengan capital jakarta dan poulasi 250
country1={'indonesia':'jakarta','population':250}
country.update(country1)

print(country)

dict_values(['berlin', 80.62])
{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': 'jakarta', 'population': 250}


Expected Output:

80.62

{'spain': {'capital': 'madrid', 'population': 46.77}, 'france': {'capital': 'paris', 'population': 66.03}, 'germany': {'capital': 'berlin', 'population': 80.62}, 'norway': {'capital': 'oslo', 'population': 5.084}, 'indonesia': {'capital': 'jakarta', 'population': 250}}

<h2>Soal 11: Loop Dictionary</h2>
    
Lengkapi kode untuk menghasilkan suatu output yang di harapkan

In [34]:
country = { 
           'spain': { 'capital':'madrid', 'population':46.77 },
           'france': { 'capital':'paris', 'population':66.03 },
           'germany': { 'capital':'berlin', 'population':80.62 },
           'norway': { 'capital':'oslo', 'population':5.084 },
           'indonesia' : {'capital':'jakarta', 'population':250}
         }

for x in country:
    print('Ibukota '+x+' adalah '+country[x]['capital'])

Ibukota spain adalah madrid
Ibukota france adalah paris
Ibukota germany adalah berlin
Ibukota norway adalah oslo
Ibukota indonesia adalah jakarta


Expected Output:
    
Ibukota spain adalah madrid

Ibukota france adalah paris

Ibukota germany adalah berlin

Ibukota norway adalah oslo

Ibukota indonesia adalah jakarta



---



---



# Set

## Soal 12: Remove Duplicate using set


Hilangkan nilai duplikat dari sebuah objek list dengan menggunakan cara set sehingga menjadi sebuah tipe set

In [37]:
obj_list = [1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 9, 10]

#using set
print(list(set(obj_list)))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


Expected output: 

{1, 2, 3, 4, 5, 6, 7, 8, 9, 10}

## Soal 13: Mengubah dan menghapus anggota set

Ubahlah dan hapus anggota set sehingga mendapatkan hasil yang diinginkan


In [52]:
set_1 = {1, 2, 3, 4, 5}

#tambahkan anggota set dengan nilai {6,7,8}
set_1.update([6,7,8])
#hapus nilai anggota set 8
set_1.remove(8)

print(set_1)

{1, 2, 3, 4, 5, 6, 7}


Expected output:

{1, 2, 3, 4, 5, 6, 7}

## Soal 14: Operasi pada Set

Carilah irisan dari ke dua set dengan menggunakan metode intersection

In [81]:
set_2 = {6, 8, 9, 10, 24}
set_3 = {6, 10, 8, 25, 13}

#intersection set
print(set_2 & set_3)
set_3.intersection(set_2) 

{8, 10, 6}


{6, 8, 10}

Expected output:


{6, 8, 10}



---



---

